Работа со строкой запроса
htmlacademy-php/813757-readme-12 pull request #10
Opened 2021-08-24 04:16 UTC by tim24ktk

2021-08-25 07:44 UTC, Shv-sergey70 requested changes

2021-08-25 07:44 UTC, Shv-sergey70 commented on index.php
> +$contentType = mysqli_fetch_all($contentResult, MYSQLI_ASSOC);
Стоит проверять на наличие mysqli ошибки при запросе и завершать работу скрипта, если не удалось выполнить запрос:
https://www.php.net/manual/en/mysqli.error.php

2021-08-25 07:44 UTC, Shv-sergey70 commented on index.php
> +}
Тут бы хорошо подошел тернарный оператор

2021-08-25 07:44 UTC, Shv-sergey70 commented on index.php
> +}
Тут бы хорошо подошел тернарный оператор

2021-08-25 07:44 UTC, Shv-sergey70 commented on index.php
> +    'ord' => $ord,
Лучше не допускать сокращений в коде в виде `ord`

2021-08-25 07:44 UTC, Shv-sergey70 commented on post.php
> +    $post = mysqli_fetch_assoc($result);
Тут нужно проверить на наличие mysqli ошибки из `mysqli_query`

2021-08-25 07:44 UTC, Shv-sergey70 commented on templates/main.php
> +                        <a class="filters__button filters__button--ellipse filters__button--all <?= $activeClass = !$_GET ? 'filters__button--active' : ''; ?>" href="/">
`$activeClass = !$_GET` - как это работает? `$_GET` это же массив параметром, возможно нужно было указать ключ?

2021-08-25 07:44 UTC, Shv-sergey70 commented on templates/main.php
> +                                    <!--закоментировал превью к видео так как выдает ошибку http://joxi.ru/Y2LP5R9iMONKk2,
В исходной разметке все выглядит также?

2021-08-28 02:02 UTC, tim24ktk commented on templates/main.php
> +                                    <!--закоментировал превью к видео так как выдает ошибку http://joxi.ru/Y2LP5R9iMONKk2,
В исходной разметке так и выглядело http://joxi.ru/KAx8LWlcvpkG8A

2021-08-28 05:30 UTC, Shv-sergey70 commented on index.php
> +    print("Ошибка подготовки запроса: " . mysqli_error($connect));
Тут можно делать `exit`, потому что дальше скрипт выполнять нет смысла без подключения к БД

2021-08-28 05:47 UTC, merged